name: Compile Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'manuscript/**'
      - '!manuscript/scripts/py/**'
      - '.github/workflows/compile-test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'manuscript/**'
      - '!manuscript/scripts/py/**'
      - '.github/workflows/compile-test.yml'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install LaTeX and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexdiff
        
    - name: Compile manuscript without figures
      run: |
        cd manuscript
        ./compile -nf
        
    - name: Upload compiled PDF
      uses: actions/upload-artifact@v3
      with:
        name: manuscript-pdf
        path: manuscript/main/manuscript.pdf
        if-no-files-found: error