# Timestamp: "2025-09-27 18:59:28 (ywatanabe)"
# File: ./paper/config/config_supplementary.yaml

verbosity:
  pdflatex: true
  bibtex: true

paths:
  doc_root_dir: "./02_supplementary"
  doc_log_dir: "./02_supplementary/logs"
  global_log_file: "./02_supplementary/logs/global.log"
  base_tex: "./02_supplementary/base.tex"
  compiled_tex: "./02_supplementary/supplementary.tex"
  compiled_pdf: "./02_supplementary/supplementary.pdf"
  diff_tex: "./02_supplementary/supplementary_diff.tex"
  diff_pdf: "./02_supplementary/supplementary_diff.pdf"
  archive_dir: "./02_supplementary/archive"
  version_counter_txt: "./02_supplementary/archive/.version_counter.txt"
  texlive_apptainer_sif: "./.cache/containers/texlive_container.sif"
  mermaid_apptainer_sif: "./.cache/containers/mermaid_container.sif"
  imagemagick_apptainer_sif: "./.cache/containers/imagemagick_container.sif"
  
figures:
  dir: "./02_supplementary/contents/figures"
  caption_media_dir: "./02_supplementary/contents/figures/caption_and_media"
  jpg_dir: "./02_supplementary/contents/figures/caption_and_media/jpg_for_compilation"
  compiled_dir: "./02_supplementary/contents/figures/compiled"
  compiled_file: "./02_supplementary/contents/figures/compiled/FINAL.tex"
  templates_dir: "./shared/templates/figures"
  template_pptx: "./shared/templates/figures/.00_TEMPLATE.pptx"  
  template_tif: "./shared/templates/figures/.00_TEMPLATE.tif"  
  template_jpg: "./shared/templates/figures/.00_TEMPLATE.jpg"
  template_jnb: "./shared/templates/figures/.00_TEMPLATE.JNB"  

tables:
  dir: "./02_supplementary/contents/tables"
  caption_media_dir: "./02_supplementary/contents/tables/caption_and_media"
  compiled_dir: "./02_supplementary/contents/tables/compiled"
  compiled_file: "./02_supplementary/contents/tables/compiled/FINAL.tex"

misc:
  wordcount_dir: "./02_supplementary/contents/wordcounts"
  tree_txt: "./02_supplementary/docs/tree.txt"

# EOF