# Timestamp: "2025-09-28 20:19:34 (ywatanabe)"
# File: ./paper/config/config_manuscript.yaml

verbosity:
  pdflatex: true
  bibtex: true

paths:
  doc_root_dir: "./01_manuscript"
  doc_log_dir: "./01_manuscript/logs"
  global_log_file: "./01_manuscript/logs/global.log"
  base_tex: "./01_manuscript/base.tex"
  compiled_tex: "./01_manuscript/manuscript.tex"
  compiled_pdf: "./01_manuscript/manuscript.pdf"
  diff_tex: "./01_manuscript/manuscript_diff.tex"
  diff_pdf: "./01_manuscript/manuscript_diff.pdf"
  archive_dir: "./01_manuscript/archive"
  version_counter_txt: "./01_manuscript/archive/.version_counter.txt"
  texlive_apptainer_sif: "./.cache/containers/texlive_container.sif"
  mermaid_apptainer_sif: "./.cache/containers/mermaid_container.sif"
  imagemagick_apptainer_sif: "./.cache/containers/imagemagick_container.sif"
  
figures:
  dir: "./01_manuscript/contents/figures"
  caption_media_dir: "./01_manuscript/contents/figures/caption_and_media"
  jpg_dir: "./01_manuscript/contents/figures/caption_and_media/jpg_for_compilation"
  compiled_dir: "./01_manuscript/contents/figures/compiled"
  compiled_file: "./01_manuscript/contents/figures/compiled/FINAL.tex"
  templates_dir: "./shared/templates/figures"
  template_pptx: "./shared/templates/figures/.00_TEMPLATE.pptx"  
  template_tif: "./shared/templates/figures/.00_TEMPLATE.tif"  
  template_jpg: "./shared/templates/figures/.00_TEMPLATE.jpg"
  template_jnb: "./shared/templates/figures/.00_TEMPLATE.JNB"  
  
tables:
  dir: "./01_manuscript/contents/tables"
  caption_media_dir: "./01_manuscript/contents/tables/caption_and_media"
  compiled_dir: "./01_manuscript/contents/tables/compiled"
  compiled_file: "./01_manuscript/contents/tables/compiled/FINAL.tex"

misc:
  wordcount_dir: "./01_manuscript/contents/wordcounts"
  tree_txt: "./01_manuscript/docs/tree.txt"

hot-recompile:
  enabled: true
  mode: "restart"  # "restart" or "wait" - how to handle ongoing compilations
  stable_link: "./01_manuscript/manuscript-latest.pdf"  # Symlink (use rsync -L to follow)
  watching_files:
    # Content files
    - "./01_manuscript/contents/*.tex"
    - "./01_manuscript/contents/**/*.tex"
    - "./01_manuscript/base.tex"
    # Tables
    - "./01_manuscript/contents/tables/caption_and_media/*.csv"
    - "./01_manuscript/contents/tables/caption_and_media/*.tex"
    # Figures
    - "./01_manuscript/contents/figures/caption_and_media/*.tex"
    - "./01_manuscript/contents/figures/caption_and_media/*.jpg"
    - "./01_manuscript/contents/figures/caption_and_media/*.png"
    - "./01_manuscript/contents/figures/caption_and_media/*.tif"
    - "./01_manuscript/contents/figures/caption_and_media/*.pptx"
    - "./01_manuscript/contents/figures/caption_and_media/*.mmd"
    # Bibliography
    - "./01_manuscript/contents/**/*.bib"
    # Config
    - "./config/*.yaml"
    # Scripts (optional)
    - "./scripts/shell/modules/*.sh"
    - "./scripts/python/*.py"

# EOF